name: Website Integrate and Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    pull:
      runs-on: [GV-DATA01]

      steps:
        - name: Pull repo
          run: cd /D U:\Shares\WebShare\imryanfrom.it & git pull origin main
          shell: cmd

    build:
      runs-on: [GV-WEB01]
      needs: pull

      steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v3

      - name: Enter directory
        run: pushd \\gv-data01\Shares\WebShare\imryanfrom.it
        shell: cmd
  
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true
  
      - name: Update Hugo Modules
        run: hugo mod tidy
  
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install node modules
        run: |
          hugo mod npm pack
          npm install
          
      - name: Build
        run: hugo --minify

      - name: Exit directory
        run: popd
        shell: cmd

    IIS_Restart:
      runs-on: [GV-WEB01]
      needs: build

      steps:
        - name: Restart IIS
          run: iisreset
          shell: cmd