name: Website Integrate and Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    pull:
      runs-on: [GV-DATA01]
      # Updates repo on file server
      steps:
        - name: Pull repo
          run: cd /D U:\Shares\WebShare\imryanfrom.it & git pull origin master
          shell: cmd

    build:
      runs-on: [GV-WEB01]
      needs: pull

      steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v3

      - name: Enter directory
        run: pushd \\gv-data01\Shares\WebShare\imryanfrom.it
        shell: cmd

      - name: Update Hugo Modules
        run: hugo mod tidy
        shell: cmd

      - name: Install node modules
        run: |
          hugo mod npm pack
          npm install
        shell: cmd
          
      - name: Build
        run: hugo --minify
        shell: cmd

      - name: Exit directory
        # For some reason gactions thinks this fails when it doesn't, so added continue-on-error
        continue-on-error: true
        run: popd
        shell: cmd

    IIS_Restart:
      runs-on: [GV-WEB01]
      needs: build

      steps:
        - name: Restart IIS
          run: iisreset
          shell: cmd