name: Website Integrate and Deploy

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    pull:
      runs-on: [GV-DATA01]
      # Updates repo on file server
      steps:
        - name: Pull repo
          run: cd /D U:\Shares\WebShare\imryanfrom.it & git pull origin master
          shell: cmd

    build:
      runs-on: [GV-WEB01]
      needs: pull

      steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v3

      - name: Update Hugo Modules
        run: |
          pushd \\gv-data01\Shares\WebShare\imryanfrom.it 
          hugo mod tidy
        shell: cmd

      - name: Install node modules
        run: |
          pushd \\gv-data01\Shares\WebShare\imryanfrom.it 
          hugo mod npm pack
          npm install
        shell: cmd
          
      - name: Build
        run: |
          pushd \\gv-data01\Shares\WebShare\imryanfrom.it
          hugo --minify
        shell: cmd